### ISSUE TITLE
Slow backend initialization

### ISSUE THREAD

**Issue by zenker** [ChimeraTK/DeviceAccess-DoocsBackend#1]
After installing the latest chimeraTK Version, initializing the doocs backend takes approx. 20 seconds. After the backend can be used without problems.

This can be checked using e.g. Qthardmon connecting to any DOOCS server. When opening the device Qthardmon freezes.

**Comment by killenb** [comment]
Unfortunately, this currently is expected behaviour. The backend is filling the register catalogue when opened which unfortunately takes time. There are plans for a "lazy loading" only when the register catalogue is requested, but we don't have a good strategy yet. The old version, which did not load the catalogue, could not be used with QtHardMon, for instance.

**Comment by mhier** [comment]
Actually, the current behaviour should already be to fill the catalogue only when it is requested ("lazy loading"). This would make normal applications fast, since they don't need the catalogue. Applications like QtHardMon could make a proper notification to the user themselves, since it should be know that obtaining the catalogue can take some time. Printing something to the console in DeviceAccess should be avoided, since the application has no control over this.

Can you please confirm whether you see this behaviour also in normal applications which do not request the catalogue?

**Comment by zenker** [comment]
I'm not sure if the LLRF Server requests the catalogue, but with this application I experienced the slow initialization.

**Comment by mhier** [comment]
Are you using the latest version of the DoocsBackend there? There was a bug in earlier versions which have been fixed.

**Comment by zenker** [comment]
Yes I'm using DoocsBackend version 0.12. As I said, before switching to that version I never realised such problems.
